name: Publish Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  REGISTRY_HOSTNAME: ghcr.io

jobs:
  release:
    runs-on: ubuntu-latest
    name: Publish Docker Image
    steps:
      - uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_HOSTNAME }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        if: github.ref_type == 'branch'
        with:
          push: true
          tags: ${{ env.REGISTRY_HOSTNAME }}/${{ github.repository }}:latest
          platforms: linux/amd64,linux/arm64

      - name: Build and push
        uses: docker/build-push-action@v2
        if: github.ref_type == 'tag'
        with:
          push: true
          tags: ${{ env.REGISTRY_HOSTNAME }}/${{ github.repository }}:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64
